spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/synpulse8_test?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  sql:
    init:
      schema-locations: classpath*:sql/schema.sql
      mode: always
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    database: 0
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFAK_PORT}
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      max-poll-records: 1000
    listener:
      type: batch
      poll-timeout: 1000
    producer:
      acks: 1

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
  type-aliases-package: com.oliver

server:
  port: 8889

jwt:
  key: ad6fbd4b-659d-4cbe-8b2d-9376f5232872
  expiration:
    time: 60000 # 1 * 60 * 1000 (1 minute)

kafka-topic: test

thread-pool:
  core-pool-size: 8
  max-pool-size: 16
  queue-capacity: 5