spring:
  datasource:
    url: jdbc:localhost://mysql:3306/synpulse8?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  sql:
    init:
      schema-locations: classpath*:sql/schema.sql
      mode: always
  redis:
    host: localhost
    port: 6379
    database: 0
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      max-poll-records: 500
    listener:
      type: batch
      poll-timeout: 1000
    producer:
      acks: 1

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
  type-aliases-package: com.oliver

server:
  port: 8889

jwt:
  key: ad6fbd4b-659d-4cbe-8b2d-9376f5232872
  expiration:
    time: 28800000 # 8 * 60 * 60 * 1000 (8 hours)

kafka-topic: transactions

logging:
  level:
    com:
      oliver:
        accountBackend: error
        apiGateway: error
  file:
    name: log/sys.log


thread-pool:
  core-pool-size: 8
  max-pool-size: 16
  queue-capacity: 5


