kind: Service
apiVersion: v1
metadata:
  name: synpulse8-backend
  namespace: synpulse8
spec:
  type: LoadBalancer
  selector:
    app: synpulse8-backend
  ports:
    - name: http
      protocol: TCP
      port: 8889
      targetPort: 8889