spring:
  datasource:
    url: jdbc:mysql://localhost:3306/synpulse8_test?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  sql:
    init:
      schema-locations: classpath*:sql/schema.sql
      mode: always
  redis:
    host: localhost
    port: 6379
    database: 1

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
  type-aliases-package: com.oliver

jwt:
  key: ad6fbd4b-659d-4cbe-8b2d-9376f5232872
  expiration:
    time: 60000 # 1 * 60 * 1000 (1 minute)